services:
  backend:
    build: ./backend
    container_name: archon_backend
    depends_on:
      - db
    environment:
      ARCHON_DB_URL: postgresql+asyncpg://admin:password@db:5432/archondb
    ports:
      - "8000:8000"
    volumes:
      - archon_files:/var/lib/archon/files

  db:
    image: postgres:18
    container_name: archon_database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: archondb
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d:Z
      - archon_data:/var/lib/postgresql
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: archon_pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@archon.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  archon_files:
  archon_data:
  pgadmin_data:
